# Generated by Django 5.1.6 on 2025-05-14 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('first_name', models.CharField(help_text="Patient's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Patient's last name", max_length=100)),
                ('patient_number', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(help_text="Patient's age in years")),
                ('sex', models.IntegerField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', help_text="Patient's sex")),
                ('admitting_diagnosis', models.TextField(default='Pain', help_text="Patient's initial diagnosis")),
                ('Final_diagnosis', models.TextField(default='Pain', help_text="Patient's final diagnosis")),
                ('contact_number', models.BigIntegerField(help_text="Patient's contact number")),
                ('date_of_birth', models.DateField(help_text="Patient's date of birth")),
                ('room_number', models.IntegerField(help_text="Patient's assigned room number")),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Rhnull', 'Rhnull')], default='O+', help_text="Patient's blood group", max_length=100)),
                ('chief_complaint', models.TextField(default='Pain', help_text="Primary reason for patient's visit")),
                ('middle_name', models.CharField(blank=True, help_text="Patient's middle name (optional)", max_length=100)),
                ('bed_number', models.IntegerField(default=1, help_text="Patient's assigned bed number")),
                ('religion', models.CharField(blank=True, help_text="Patient's religious preference", max_length=100)),
                ('diet', models.CharField(default='DAT', help_text="Patient's dietary requirements or restrictions", max_length=100)),
                ('height', models.DecimalField(decimal_places=2, default=0, help_text="Patient's height in centimeters", max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text="Patient's weight in kilograms", max_digits=5)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether the patient record is archived')),
                ('date_archived', models.DateTimeField(blank=True, help_text='Date and time when the patient record was archived', null=True)),
            ],
            options={
                'db_table': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Emergencycontactdetails',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('relation_to_patient', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('patient_number', models.OneToOneField(db_column='patient_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.patients')),
            ],
            options={
                'db_table': 'EmergencyContactDetails',
            },
        ),
    ]
