# Generated by Django 5.1.6 on 2025-03-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('bed_number', models.IntegerField()),
                ('patient_number', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('contact_number', models.BigIntegerField()),
                ('date_of_birth', models.DateField()),
                ('room_number', models.IntegerField()),
            ],
            options={
                'db_table': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Emergencycontactdetails',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('relation_to_patient', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('patient_number', models.OneToOneField(db_column='patient_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.patients')),
            ],
            options={
                'db_table': 'EmergencyContactDetails',
            },
        ),
    ]
