# Generated by Django 5.1.6 on 2025-05-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', help_text="Patient's sex", max_length=10),
        ),
    ]
