# Generated by Django 5.1.6 on 2025-04-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
