# Generated by Django 5.1.6 on 2025-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Final_diagnosis',
            field=models.TextField(blank=True, help_text="Patient's final diagnosis"),
        ),
    ]
