# Generated by Django 5.1.6 on 2025-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
