# Generated by Django 5.1.6 on 2025-06-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_final_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
