# Generated by Django 5.1.6 on 2025-06-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patients_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontactdetails',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
