# Generated by Django 5.1.6 on 2025-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patients_date_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Other', 'Other')], default='O+', help_text="Patient's blood group", max_length=100),
        ),
        migrations.AddField(
            model_name='patients',
            name='chief_complaint',
            field=models.TextField(default='Pain', help_text="Primary reason for patient's visit"),
        ),
        migrations.AddField(
            model_name='patients',
            name='diet',
            field=models.CharField(blank=True, help_text="Patient's dietary requirements or restrictions", max_length=100),
        ),
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text="Patient's gender", max_length=1),
        ),
        migrations.AddField(
            model_name='patients',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Patient's height in centimeters", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='religion',
            field=models.CharField(blank=True, help_text="Patient's religious preference", max_length=100),
        ),
        migrations.AddField(
            model_name='patients',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Patient's weight in kilograms", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(help_text="Patient's age in years"),
        ),
        migrations.AlterField(
            model_name='patients',
            name='bed_number',
            field=models.IntegerField(blank=True, help_text="Patient's assigned bed number", null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='contact_number',
            field=models.BigIntegerField(help_text="Patient's contact number"),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_archived',
            field=models.DateTimeField(blank=True, help_text='Date and time when the patient record was archived', null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(help_text="Patient's date of birth"),
        ),
        migrations.AlterField(
            model_name='patients',
            name='first_name',
            field=models.CharField(help_text="Patient's first name", max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether the patient record is archived'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='last_name',
            field=models.CharField(help_text="Patient's last name", max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='middle_name',
            field=models.CharField(blank=True, help_text="Patient's middle name (optional)", max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='room_number',
            field=models.IntegerField(help_text="Patient's assigned room number"),
        ),
    ]
