# Generated by Django 5.1.6 on 2025-06-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_emergencycontactdetails_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Final_diagnosis',
            field=models.TextField(blank=True, default='', help_text="Patient's final diagnosis"),
        ),
    ]
