# Generated by Django 5.1.6 on 2025-05-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patients_blood_group_patients_chief_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='bed_number',
            field=models.IntegerField(blank=True, default=1, help_text="Patient's assigned bed number"),
        ),
        migrations.AlterField(
            model_name='patients',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Patient's height in centimeters", max_digits=5),
        ),
        migrations.AlterField(
            model_name='patients',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Patient's weight in kilograms", max_digits=5),
        ),
    ]
