# Generated by Django 5.1.6 on 2025-03-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('Medication_name', models.CharField(max_length=100)),
                ('Dosage', models.CharField(max_length=100)),
                ('Dosage_Unit', models.CharField(max_length=100)),
                ('Medication_Time', models.TimeField()),
                ('Frequency', models.TimeField()),
                ('Medication_notes', models.TextField()),
                ('patient_number', models.OneToOneField(db_column='patient_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.patients')),
            ],
            options={
                'db_table': 'Medications',
            },
        ),
    ]
