# Generated by Django 5.1.6 on 2025-03-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication_name', models.CharField(max_length=100)),
                ('Dosage', models.CharField(max_length=100)),
                ('Dosage_Unit', models.CharField(max_length=100)),
                ('Medication_Time', models.TimeField()),
                ('Frequency', models.TimeField()),
                ('Medication_notes', models.TextField()),
                ('schedule_id', models.IntegerField(blank=True, null=True)),
                ('patient_number', models.ForeignKey(db_column='patient_number', on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
            options={
                'db_table': 'Medications',
                'unique_together': {('patient_number', 'schedule_id')},
            },
        ),
    ]
