# Generated by Django 5.1.6 on 2025-05-14 12:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication_name', models.CharField(max_length=100)),
                ('Medication_form', models.CharField(max_length=100)),
                ('Medication_Time', models.TimeField()),
                ('Medication_strength', models.CharField(max_length=100)),
                ('Medication_notes', models.TextField()),
                ('Medication_unit', models.CharField(default='mg', help_text='Default unit of measurement for medication strength', max_length=100)),
                ('Frequency', models.TimeField(default=datetime.time(8, 0), help_text='Time of day when medication should be taken')),
                ('Medication_start_date', models.DateField(default=datetime.date.today, help_text='Date when medication regimen begins')),
                ('Medication_end_date', models.DateField(default=datetime.date.today, help_text='Date when medication regimen ends')),
                ('Medication_route', models.CharField(choices=[('Oral', 'Oral'), ('Intramuscular', 'Intramuscular'), ('Intravenous', 'Intravenous'), ('Subcutaneous', 'Subcutaneous'), ('Topical', 'Topical'), ('Inhalation', 'Inhalation'), ('Sublingual', 'Sublingual'), ('Transdermal', 'Transdermal'), ('Rectal', 'Rectal'), ('Intranasal', 'Intranasal'), ('Ocular', 'Ocular'), ('Vaginal', 'Vaginal'), ('Other', 'Other')], default='Oral', help_text='Method of medication administration', max_length=100)),
                ('schedule_id', models.IntegerField(blank=True, null=True)),
                ('patient_number', models.ForeignKey(db_column='patient_number', on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
            options={
                'db_table': 'Medications',
                'unique_together': {('patient_number', 'schedule_id')},
            },
        ),
    ]
