# Generated by Django 5.1.6 on 2025-05-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='Medication_form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Patch', 'Patch'), ('Other', 'Other')], default='Tablet', max_length=100),
        ),
        migrations.AlterField(
            model_name='medications',
            name='Medication_strength',
            field=models.CharField(choices=[('mL', 'mL'), ('mcg', 'mcg'), ('mg', 'mg'), ('%', '%'), ('g', 'g')], default='mg', max_length=100),
        ),
    ]
