# Generated by Django 5.1.6 on 2025-05-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medications_medication_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='Medication_strength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medications',
            name='Medication_unit',
            field=models.CharField(choices=[('mL', 'mL'), ('mcg', 'mcg'), ('mg', 'mg'), ('%', '%'), ('g', 'g')], default='mg', help_text='Default unit of measurement for medication strength', max_length=100),
        ),
    ]
