# Generated by Django 5.1.6 on 2025-05-13 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20250325_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medications',
            old_name='Dosage',
            new_name='Medication_form',
        ),
        migrations.RenameField(
            model_name='medications',
            old_name='Dosage_Unit',
            new_name='Medication_strength',
        ),
        migrations.AddField(
            model_name='medications',
            name='Medication_end_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when medication regimen ends'),
        ),
        migrations.AddField(
            model_name='medications',
            name='Medication_route',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Intramuscular', 'Intramuscular'), ('Intravenous', 'Intravenous'), ('Subcutaneous', 'Subcutaneous'), ('Topical', 'Topical'), ('Inhalation', 'Inhalation'), ('Sublingual', 'Sublingual'), ('Transdermal', 'Transdermal'), ('Rectal', 'Rectal'), ('Intranasal', 'Intranasal'), ('Ocular', 'Ocular'), ('Vaginal', 'Vaginal'), ('Other', 'Other')], default='Oral', help_text='Method of medication administration', max_length=100),
        ),
        migrations.AddField(
            model_name='medications',
            name='Medication_start_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when medication regimen begins'),
        ),
        migrations.AddField(
            model_name='medications',
            name='Medication_unit',
            field=models.CharField(default='mg', help_text='Default unit of measurement for medication strength', max_length=100),
        ),
        migrations.AlterField(
            model_name='medications',
            name='Frequency',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Time of day when medication should be taken'),
        ),
    ]
