# Generated by Django 5.1.6 on 2025-05-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medications_medication_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='administered',
            field=models.BooleanField(default=False, help_text='Indicates whether the medication has been administered'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='Medication_notes',
            field=models.TextField(blank=True),
        ),
    ]
