# Generated by Django 5.1.6 on 2025-05-24 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medications_administered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='Frequency',
            field=models.DurationField(default=datetime.timedelta(seconds=28800), help_text='Duration between medication administrations'),
        ),
    ]
