# Generated by Django 5.1.6 on 2025-05-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_alter_medications_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='Frequency_type',
            field=models.CharField(choices=[('Od', 'Once Daily'), ('Bid', 'Twice Daily'), ('Tid', 'Thrice Daily'), ('Qid', 'Four times Daily'), ('Other', 'Other')], default='Od', help_text='Frequency type for medication administration', max_length=50),
        ),
    ]
