# Generated by Django 5.1.6 on 2025-05-25 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_medications_frequency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='Medication_end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date when medication regimen ends'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='Medication_unit',
            field=models.CharField(choices=[('ml', 'mL'), ('mcg', 'mcg'), ('mg', 'mg'), ('%', '%'), ('g', 'g')], default='mg', help_text='Default unit of measurement for medication strength', max_length=100),
        ),
    ]
