# Generated by Django 5.1.6 on 2025-05-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_alter_medications_medication_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='Frequency_type',
            field=models.CharField(choices=[('OD', 'Once Daily'), ('BID', 'Twice Daily'), ('TID', 'Thrice Daily'), ('QID', 'Four times Daily'), ('Other', 'Other')], default='OD', help_text='Frequency type for medication administration', max_length=50),
        ),
    ]
