# Generated by Django 5.1.6 on 2025-05-25 06:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_alter_medications_frequency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_doses', to='medications.medications')),
            ],
            options={
                'ordering': ['-administered_time'],
            },
        ),
    ]
