# Generated by Django 5.1.6 on 2025-05-25 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0009_administered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='Frequency',
            field=models.DurationField(default=datetime.timedelta(seconds=28800), help_text='Duration between medication administrations', null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='Medication_end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date when medication regimen ends', null=True),
        ),
    ]
