# Generated by Django 5.1.6 on 2025-05-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0010_alter_medications_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='Frequency',
            field=models.DurationField(blank=True, help_text='Duration between medication administrations', null=True),
        ),
    ]
