# Generated by Django 5.1.6 on 2025-05-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0011_alter_medications_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='physicianID',
            field=models.CharField(default='e', help_text='ID of the physician prescribing the medication', max_length=100),
            preserve_default=False,
        ),
    ]
