# Generated by Django 5.1.6 on 2025-04-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=50)),
                ('alert_sound', models.CharField(default='default', max_length=100)),
            ],
        ),
    ]
