# Generated by Django 5.1.6 on 2025-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
