# Generated by Django 5.1.6 on 2025-05-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logs_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='log_message_extended',
            field=models.TextField(blank=True),
        ),
    ]
