/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/directory`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loginstyles`; params?: Router.UnknownInputParams; } | { pathname: `/logs`; params?: Router.UnknownInputParams; } | { pathname: `/logstyles`; params?: Router.UnknownInputParams; } | { pathname: `/registernew`; params?: Router.UnknownInputParams; } | { pathname: `/registerstyle`; params?: Router.UnknownInputParams; } | { pathname: `/viewpatient`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/sidebar`; params?: Router.UnknownInputParams; } | { pathname: `/components/sidebarstyle`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `/directory`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/loginstyles`; params?: Router.UnknownOutputParams; } | { pathname: `/logs`; params?: Router.UnknownOutputParams; } | { pathname: `/logstyles`; params?: Router.UnknownOutputParams; } | { pathname: `/registernew`; params?: Router.UnknownOutputParams; } | { pathname: `/registerstyle`; params?: Router.UnknownOutputParams; } | { pathname: `/viewpatient`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/sidebar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/sidebarstyle`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/calendar${`?${string}` | `#${string}` | ''}` | `/directory${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/loginstyles${`?${string}` | `#${string}` | ''}` | `/logs${`?${string}` | `#${string}` | ''}` | `/logstyles${`?${string}` | `#${string}` | ''}` | `/registernew${`?${string}` | `#${string}` | ''}` | `/registerstyle${`?${string}` | `#${string}` | ''}` | `/viewpatient${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/sidebar${`?${string}` | `#${string}` | ''}` | `/components/sidebarstyle${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/directory`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loginstyles`; params?: Router.UnknownInputParams; } | { pathname: `/logs`; params?: Router.UnknownInputParams; } | { pathname: `/logstyles`; params?: Router.UnknownInputParams; } | { pathname: `/registernew`; params?: Router.UnknownInputParams; } | { pathname: `/registerstyle`; params?: Router.UnknownInputParams; } | { pathname: `/viewpatient`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/sidebar`; params?: Router.UnknownInputParams; } | { pathname: `/components/sidebarstyle`; params?: Router.UnknownInputParams; };
    }
  }
}
